### ISSUE TITLE
std * 2

### ISSUE THREAD

**Issue by Chelimin** [sarajcev/singapore#1]
Hi great job here, have you been to Singapore before? You sound familiar with the market...
Was just wondering, in your train_and_evaluate function, why do you take np.std(scores)*2 ? (last line)

```
def train_and_evaluate(model, X, y):
    model.fit(X, y)
    print('Score on training set: {:g}'.format(model.score(X, y)))
    # k-fold cross validation iterator of 5 folds
    cv = KFold(X.shape[0], 5, shuffle=True)
    scores = cross_val_score(model, X, y, cv=cv)
    print('Score using 5-fold cross-validation: {:g} +/- {:g}'.format(np.mean(scores), np.std(scores)*2))
```

**Comment by sarajcev** [comment]
I've been to the Singapore as a tourist and was fascinated by the city. I'm not familiar with the real estate market.

The code `np.std(score)*2` computes the range of two standard deviations of expected scores from the 5-fold cross-validations and reports the plausible range around the mean as: mean +/- 2*std. Hope this helps.

**Comment by Chelimin** [comment]
hi Peter, why does it have to be x 2? Shouldn't it just be mean +/- std ?

**Comment by sarajcev** [comment]
It doesn't have to be x 2. You can report mean +/- std just as well.
